### ISSUE TITLE
Parsing LocalDate from string return wrong value and no exception

### ISSUE THREAD

**Issue by masterdany88** [foal/gwt-time#10]
When I wonna parse:
```        String dateToParse = "2021-09-31";```
with pattern:
```"yyyy-MM-dd"```
as follow:
```        LocalDate.parse(dateToParse, DateTimeFormatter.ofPattern("yyyy-MM-dd"));```
I am getting result:
2021-09-30
There should be an exception.

Creating LocalDate manually as follow:
```LocalDate expectedParsedDate = LocalDate.of(2021, 9, 31);```
will result in exception:
```java.time.DateTimeException: Invalid date 'SEPTEMBER 31'```

**Comment by foal** [comment]
Hi, thanks for the report. 

This is no error, but the feature. The GWT implementation behaves in the same way as Java (on JVM).

By default the `DateTimeFormatter` class use `ResolverStyle.SMART`, which leads to this conversation (31 -> 30). 

To archive the expected exception you should set up the DateTimeFormatter to use `ResolverStyle.STRICT` by `withResolverStyle` method.

```java
DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd").withResolverStyle(ResolverStyle.STRICT);
LocalDate res = LocalDate.parse("2021-09-31", formatter);
```
