### ISSUE TITLE
Compilation issue in 1.4.15

### ISSUE THREAD

**Issue by dnouls** [foal/gwt-time#7]
[INFO]          [ERROR] Errors in 'org/jresearch/threetenbp/gwt/time/super/java/time/format/SimpleDateTimeTextProvider.java'
[INFO]             [ERROR] Line 339: BC cannot be resolved or is not a field
[INFO]             [ERROR] Line 340: AD cannot be resolved or is not a field
[INFO]             [ERROR] Line 345: BC cannot be resolved or is not a field
[INFO]             [ERROR] Line 346: AD cannot be resolved or is not a field
[INFO]             [ERROR] Line 351: BC cannot be resolved or is not a field
[INFO]             [ERROR] Line 352: AD cannot be resolved or is not a field
[INFO]          Tracing compile failure path for type 'java.time.format.SimpleDateTimeTextProvider'
[INFO]             [ERROR] Errors in 'org/jresearch/threetenbp/gwt/time/super/java/time/format/SimpleDateTimeTextProvider.java'
[INFO]                [ERROR] Line 346: AD cannot be resolved or is not a field
[INFO]                [ERROR] Line 352: AD cannot be resolved or is not a field
[INFO]                [ERROR] Line 339: BC cannot be resolved or is not a field
[INFO]                [ERROR] Line 345: BC cannot be resolved or is not a field
[INFO]                [ERROR] Line 351: BC cannot be resolved or is not a field
[INFO]                [ERROR] Line 340: AD cannot be resolved or is not a field
[INFO]          [ERROR] Hint: Check that the type name 'java.time.format.SimpleDateTimeTextProvider' is really what you meant
[INFO]          [ERROR] Hint: Check that your classpath includes all required source roots

**Comment by foal** [comment]
Looks like an error 

SimpleDateTimeTextProvider use the java.util.Calendar and java.util.GregorianCalendar that are not emulated by GWT

**Comment by dnouls** [comment]
I have de.knightsoft-net:gwt-bean-validators (1.1.11) in my classpath and that one includes gwt-commons-lang3 which seems to have some basic Calendar and GregorianCalendar emulation. That is what made it a bit confusing to me.

Maybe if I use a newer version of gwt-commons-lang3 it will work. I noticed that that component has switched to using gwt-time. But unfortunately it also uses gwt 2.9 (which gives compilation errors on some of my code, with some complex generics usage).

**Comment by dnouls** [comment]
I see that in https://gitlab.com/ManfredTremmel/gwt-commons-lang3/-/tags/v3.10-3 that the author added some extra emulation to be ale to use gwt-time.

**Comment by foal** [comment]
Check the new release. The issue should be fixed

**Comment by dnouls** [comment]
Nice, thanks for that quick fix!
