### ISSUE TITLE
Support for time zones

### ISSUE THREAD

**Issue by pvlnsk** [foal/gwt-time#8]
Hello! I am having a problem when defining time zones:
```
run:
ZoneId zone = ZoneId.systemDefault();
result:
Can't resolve system default zone Asia/Novosibirsk: No time-zone data files registered. Fallback to zone offset null
```
how can support ZoneId or what is the alternative?

**Comment by foal** [comment]
Did you have dependency on org.jresearch.gwt.time.tzdb module?
```xml
<dependency>
	<groupId>org.jresearch.gwt.time</groupId>
	<artifactId>org.jresearch.gwt.time.tzdb</artifactId>
</dependency>
```

**Comment by foal** [comment]
I will update ReadMe with possible dependency options. For now, you can check this page - https://github.com/foal/gwt-time/wiki/Different-setups-for-projects-using-gwt-time.
